### PR TITLE
Feature/copyhexcode

### PR DESCRIPTION
**Pull request by tfettig22**
Add copyHexCode function and add some hover effects to the hex codes to visualize being able to copy them.

### CODE REVIEW

**Comment by aspitz1** [comment]
Can we add the copy hex to the saved palette too, like if you click on a color? Maybe instead of the plus cursor (or in addition to) we could do a tooltip that says 'click to copy to clipboard'. Alternatively after it was clicked there could be a tool tip that says 'copied to clipboard'

That being said I am happy to merge it in as is with the possibility of fiddling with it later.

**Review by aspitz1 — APPROVED** [review]
Code looks good to me.

**Comment by dstavis** [comment]
> 

Yeah this sounds awesome but I'd call it a separate feature. Would you be down to add it to the CYOA group on Monday?

**Comment by dstavis** [comment]
Dang!! Just demo'd the copy hexcode feature and now I REALLY want to see the hexcode style react when the user clicks it. I'd love to see a hexcode:active style so that it changes appearance when it's clicked. And now that Anna has planted the idea in my head, I desperately want to see a "Copied!" / "Copied to clipboard!" tooltip pop up and fade away 😭

**Comment by dstavis** [comment]
> Dang!! Just demo'd the copy hexcode feature and now I REALLY want to see the hexcode style react when the user clicks it. I'd love to see a hexcode:active style so that it changes appearance when it's clicked. And now that Anna has planted the idea in my head, I desperately want to see a "Copied!" / "Copied to clipboard!" tooltip pop up and fade away 😭

I think for now I'll go ahead and merge your PR, and let's call what I requested a new feature that we can open a separate PR for. I'll add it in Monday.

**Pull request merged**
